name: Kirsten Sonstegard
favicon: null
layout_spectrum: 0.74241
typography_spectrum: 0.50267
title: Action Associates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ce6b73'
    - '#f2c6c8'
    - '#9e9b8a'
    - '#403824'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.7605658173561096
  rhythmicContrast: 1
purpose: []
